### ISSUE TITLE
Does not display Unicode name

### ISSUE THREAD

**Issue by uralbash** [jszakmeister/rst2ctags#2]
For example:

```rst
Section1
========

section2
--------

секция3
-------

section4
--------

Section5
========
```
![_074](https://cloud.githubusercontent.com/assets/619015/6506302/dffa2ed2-c36b-11e4-8cee-924cb577527c.png)

**Comment by jszakmeister** [comment]
I assume it's UTF-8 encoded?  I suspect this is from the fact that the raw utf-8 bytes don't match the length of the underline.  I'll look into it, but patches are welcome, if you want to take a stab at it.

**Comment by uralbash** [comment]
Yes, of course UTF-8. I will try to solve the problem.
