### ISSUE TITLE
universal ctags compatability

### ISSUE THREAD

**Issue by farisachugthai** [jszakmeister/rst2ctags#9]
I don't know if this is something you intend on working towards, but currently this script doesn't seem compatible with uctags. I ran:

`python rst2ctags.py test-docs/latin1.rst`

 in a shell. i noticed that doing so created a tags file that had dropped the python tags out of the file. i wanted to have those appended, so i ran

`ctags -R --append .`

It produced the error `ctags: tags doesn't look like a tags file; I refuse to overwrite it.`

So it seems there's some incompatability with the current format and the format used by uctags.

Alternatively, if the user was provided the option to append their rst tags to their current tags file I could imagine that working as well without getting much into the nuance of the format.

**Comment by jszakmeister** [comment]
> I don't know if this is something you intend on working towards, but currently this script doesn't seem compatible with uctags. I ran:
> 
> `python rst2ctags.py test-docs/latin1.rst`
> 
> in a shell. i noticed that doing so created a tags file that had dropped the python tags out of the file.

Correct.  It at least used to be the behavior that ctags would just overwrite the file and I kept that.

> i wanted to have those appended, so i ran
> 
> `ctags -R --append .`
> 
> It produced the error `ctags: tags doesn't look like a tags file; I refuse to overwrite it.`
> 
> So it seems there's some incompatability with the current format and the format used by uctags.

I didn't realize there was an `--append` option, but I am surprised that ctags refuses to update it as I followed the guidelines in their documentation.  After some experimentation and examining of ctags source code, it expects pseudo-tags lines to still parse into 5 fields, meaning the optional comment isn't really optional--you need the `<TAB>//` at the end of the line for ctags to accept the tags file.

I'm not sure if I'll get it done tonight, but it's an easy fix and will get done soon.

**Comment by farisachugthai** [comment]
So I thought I stated this explicitly but I didn't so I apologize for that.

When I say uctags I mean universal ctags not exuberant crags. Tmk exuberant ctags doesn't have an append option. As it stands universal ctags doesn't seem compatible with this script. Hope that clarifies things.

Take your time if you think that that is the problem.

**Comment by jszakmeister** [comment]
> So I thought I stated this explicitly but I didn't so I apologize for that.
> 
> When I say uctags I mean universal ctags not exuberant crags. Tmk exuberant ctags doesn't have an append option. As it stands universal ctags doesn't seem compatible with this script. Hope that clarifies things.

No worries, I understood what you meant by uctags. :-)  And yes, what I identified is definitely the problem.  So it's a very easy fix.

**Comment by jszakmeister** [comment]
This has been fixed in master.  I'll make a new release some time this weekend.  Enjoy!

**Comment by farisachugthai** [comment]
Hahahah I'm following `HEAD` locally but I'm glad to hear it! Thank you!

**Comment by farisachugthai** [comment]
Works perfectly!!!
